CREATE TABLE fbevents (
`id` int,
`DTSTAMP` TEXT,
`LAST-MODIFIED` TEXT,
`CREATED` TEXT,
`SEQUENCE` TEXT,
`ORGANIZER` TEXT,
`MAILTO` TEXT,
`DTSTART` TEXT,
`DTEND` TEXT,
`UID` TEXT,
`SUMMARY` TEXT,
`LOCATION` TEXT,
`URL` TEXT,
`DESCRIPTION` TEXT
);